import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1782211252956 implements MigrationInterface {
    name = 'Migration1782211252956'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`tokens\` (\`tokenId\` int NOT NULL AUTO_INCREMENT, \`token\` text NOT NULL, \`tokenType\` enum ('BEARER', 'REFRESH', 'RESET') NOT NULL DEFAULT 'BEARER', \`revoked\` tinyint NOT NULL DEFAULT 0, \`expired\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`modifiedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`user_id\` int NOT NULL, PRIMARY KEY (\`tokenId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`user_id\` int NOT NULL AUTO_INCREMENT, \`user_name\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`user_code\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`email\` varchar(255) NULL, \`phone_number\` varchar(255) NULL, \`profile_poic\` varchar(255) NULL, \`DOB\` date NULL, \`created_by\` varchar(255) NULL, \`created_date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`modified_by\` varchar(255) NULL, \`modified_date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`dFlag\` tinyint NOT NULL DEFAULT 0, UNIQUE INDEX \`IDX_23351656ab098559729ac15f50\` (\`user_code\`), PRIMARY KEY (\`user_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles\` (\`role_id\` int NOT NULL AUTO_INCREMENT, \`role_name\` varchar(255) NOT NULL, \`created_by\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`modified_by\` varchar(255) NOT NULL, \`modified_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`d_flag\` tinyint NOT NULL DEFAULT 0, \`org_id\` int NOT NULL, PRIMARY KEY (\`role_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_org_branch\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`org_id\` int NOT NULL, \`branch_id\` int NOT NULL, \`role_id\` int NOT NULL, UNIQUE INDEX \`IDX_3139d4a8436851997803e8d8bb\` (\`user_id\`, \`org_id\`, \`branch_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`organisations\` (\`org_id\` int NOT NULL AUTO_INCREMENT, \`org_name\` varchar(255) NOT NULL, \`org_short_name\` varchar(255) NOT NULL, \`org_code\` varchar(255) NOT NULL, \`org_Reg_Number\` varchar(255) NULL, \`org_GST\` varchar(255) NULL, \`org_PAN\` varchar(255) NULL, \`org_GSTIN_Number\` varchar(255) NULL, \`org_FY\` varchar(255) NULL, \`org_enable_TDS_deduction\` varchar(255) NULL, \`org_TDS_deduction_type\` varchar(255) NULL, \`orgdistrict_number\` varchar(255) NULL, \`org_city\` varchar(255) NULL, \`org_state_code\` varchar(255) NULL, \`org_pin\` varchar(255) NULL, \`org_phone\` varchar(255) NULL, \`org_email\` varchar(255) NULL, \`org_registered_address\` varchar(255) NULL, \`document_type\` varchar(255) NULL, \`document\` varchar(255) NULL, \`org_charter_date\` date NULL, \`org_location\` varchar(255) NULL, \`org_logo\` varchar(255) NULL, \`enable_TDS_deduction\` varchar(255) NULL, \`deducter_type\` varchar(255) NULL, \`address\` varchar(255) NULL, \`contact_number\` varchar(255) NULL, \`fax_number\` varchar(255) NULL, \`email\` varchar(255) NULL, \`wesite\` varchar(255) NULL, \`service_tax\` varchar(255) NULL, \`dept_logo\` varchar(255) NULL, \`cash_account_number\` varchar(255) NULL, \`tan_number\` varchar(255) NULL, \`tin_number\` varchar(255) NULL, \`created_by\` varchar(255) NULL, \`created_date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`modified_by\` varchar(255) NULL, \`modified_date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`dFlag\` tinyint NOT NULL DEFAULT 0, UNIQUE INDEX \`IDX_eec854db969eca86644936bedd\` (\`org_short_name\`), UNIQUE INDEX \`IDX_d8de7df131272545f556f272e5\` (\`org_code\`), PRIMARY KEY (\`org_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`branches\` (\`branch_id\` int NOT NULL AUTO_INCREMENT, \`branch_name\` varchar(255) NOT NULL, \`branch_short_name\` varchar(255) NOT NULL, \`branch_code\` varchar(255) NOT NULL, \`created_by\` varchar(255) NULL, \`created_date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`modified_by\` varchar(255) NULL, \`modified_date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`dFlag\` tinyint NOT NULL DEFAULT 0, \`org_id\` int NULL, PRIMARY KEY (\`branch_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`modules\` (\`module_id\` int NOT NULL AUTO_INCREMENT, \`module_name\` varchar(255) NOT NULL, \`module_icon\` varchar(255) NULL, \`created_by\` varchar(255) NULL, \`created_date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`modified_by\` varchar(255) NULL, \`modified_date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`dFlag\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`module_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`pages\` (\`page_id\` int NOT NULL AUTO_INCREMENT, \`page_name\` varchar(255) NOT NULL, \`module_icon\` varchar(255) NULL, \`created_by\` varchar(255) NULL, \`created_date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`modified_by\` varchar(255) NULL, \`modified_date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`dFlag\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`page_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role_permissions\` (\`role_permission_id\` int NOT NULL AUTO_INCREMENT, \`can_read\` tinyint NOT NULL DEFAULT 0, \`can_write\` tinyint NOT NULL DEFAULT 0, \`can_update\` tinyint NOT NULL DEFAULT 0, \`can_delete\` tinyint NOT NULL DEFAULT 0, \`created_by\` varchar(255) NULL, \`created_date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`modified_by\` varchar(255) NULL, \`modified_date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`dFlag\` tinyint NOT NULL DEFAULT 0, \`role_id\` int NULL, \`page_id\` int NULL, PRIMARY KEY (\`role_permission_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_permissions\` (\`user_permission_id\` int NOT NULL AUTO_INCREMENT, \`can_read\` tinyint NOT NULL DEFAULT 0, \`can_write\` tinyint NOT NULL DEFAULT 0, \`can_update\` tinyint NOT NULL DEFAULT 0, \`can_delete\` tinyint NOT NULL DEFAULT 0, \`created_by\` varchar(255) NULL, \`created_date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`modified_by\` varchar(255) NULL, \`modified_date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`user_id\` int NOT NULL, \`page_id\` int NOT NULL, PRIMARY KEY (\`user_permission_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`tokens\` ADD CONSTRAINT \`FK_8769073e38c365f315426554ca5\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`user_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD CONSTRAINT \`FK_ba4f96af4628cc8b18e940436d8\` FOREIGN KEY (\`org_id\`) REFERENCES \`organisations\`(\`org_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_org_branch\` ADD CONSTRAINT \`FK_cb84c92ea8a7a8509fbe171d7de\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`user_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_org_branch\` ADD CONSTRAINT \`FK_55696a84c7d3a82922be700d397\` FOREIGN KEY (\`org_id\`) REFERENCES \`organisations\`(\`org_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_org_branch\` ADD CONSTRAINT \`FK_83a56256f8106e8e6269ee3f40e\` FOREIGN KEY (\`branch_id\`) REFERENCES \`branches\`(\`branch_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_org_branch\` ADD CONSTRAINT \`FK_113be9e76cafd3a07fcdae721bd\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`role_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`branches\` ADD CONSTRAINT \`FK_11a5e18b1a497189d0ec3cb5dac\` FOREIGN KEY (\`org_id\`) REFERENCES \`organisations\`(\`org_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_178199805b901ccd220ab7740ec\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`role_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_becd26d9c4332330de1cfed61a7\` FOREIGN KEY (\`page_id\`) REFERENCES \`pages\`(\`page_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_permissions\` ADD CONSTRAINT \`FK_3495bd31f1862d02931e8e8d2e8\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`user_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_permissions\` ADD CONSTRAINT \`FK_04a0f8dce7daa00fea9c192112d\` FOREIGN KEY (\`page_id\`) REFERENCES \`pages\`(\`page_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_permissions\` DROP FOREIGN KEY \`FK_04a0f8dce7daa00fea9c192112d\``);
        await queryRunner.query(`ALTER TABLE \`user_permissions\` DROP FOREIGN KEY \`FK_3495bd31f1862d02931e8e8d2e8\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_becd26d9c4332330de1cfed61a7\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_178199805b901ccd220ab7740ec\``);
        await queryRunner.query(`ALTER TABLE \`branches\` DROP FOREIGN KEY \`FK_11a5e18b1a497189d0ec3cb5dac\``);
        await queryRunner.query(`ALTER TABLE \`user_org_branch\` DROP FOREIGN KEY \`FK_113be9e76cafd3a07fcdae721bd\``);
        await queryRunner.query(`ALTER TABLE \`user_org_branch\` DROP FOREIGN KEY \`FK_83a56256f8106e8e6269ee3f40e\``);
        await queryRunner.query(`ALTER TABLE \`user_org_branch\` DROP FOREIGN KEY \`FK_55696a84c7d3a82922be700d397\``);
        await queryRunner.query(`ALTER TABLE \`user_org_branch\` DROP FOREIGN KEY \`FK_cb84c92ea8a7a8509fbe171d7de\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP FOREIGN KEY \`FK_ba4f96af4628cc8b18e940436d8\``);
        await queryRunner.query(`ALTER TABLE \`tokens\` DROP FOREIGN KEY \`FK_8769073e38c365f315426554ca5\``);
        await queryRunner.query(`DROP TABLE \`user_permissions\``);
        await queryRunner.query(`DROP TABLE \`role_permissions\``);
        await queryRunner.query(`DROP TABLE \`pages\``);
        await queryRunner.query(`DROP TABLE \`modules\``);
        await queryRunner.query(`DROP TABLE \`branches\``);
        await queryRunner.query(`DROP INDEX \`IDX_d8de7df131272545f556f272e5\` ON \`organisations\``);
        await queryRunner.query(`DROP INDEX \`IDX_eec854db969eca86644936bedd\` ON \`organisations\``);
        await queryRunner.query(`DROP TABLE \`organisations\``);
        await queryRunner.query(`DROP INDEX \`IDX_3139d4a8436851997803e8d8bb\` ON \`user_org_branch\``);
        await queryRunner.query(`DROP TABLE \`user_org_branch\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_23351656ab098559729ac15f50\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`tokens\``);
    }

}
