import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1784282953011 implements MigrationInterface {
    name = 'Migration1784282953011'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`organisations\` ADD \`org_enable_TDS_deduction\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` ADD \`org_TDS_deduction_type\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` ADD \`org_registered_address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` ADD \`document_type\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` ADD \`document\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` ADD \`org_charter_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` ADD \`enable_TDS_deduction\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` ADD \`deducter_type\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` ADD \`fax_number\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` ADD \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` ADD \`wesite\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` ADD \`service_tax\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` ADD \`dept_logo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` ADD \`cash_account_number\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` ADD \`tan_number\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` ADD \`tin_number\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`full_name\` \`full_name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone_number\` \`phone_number\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`profile_poic\` \`profile_poic\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`DOB\` \`DOB\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`modified_by\` \`modified_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`modified_by\` \`modified_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_Reg_Number\` \`org_Reg_Number\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_GST\` \`org_GST\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_PAN\` \`org_PAN\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_GSTIN_Number\` \`org_GSTIN_Number\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_FY\` \`org_FY\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`orgdistrict_number\` \`orgdistrict_number\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_city\` \`org_city\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_state_code\` \`org_state_code\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_pin\` \`org_pin\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_phone\` \`org_phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_email\` \`org_email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_location\` \`org_location\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_logo\` \`org_logo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`address\` \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`contact_number\` \`contact_number\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`modified_by\` \`modified_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`branches\` DROP FOREIGN KEY \`FK_11a5e18b1a497189d0ec3cb5dac\``);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`modified_by\` \`modified_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`org_id\` \`org_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP FOREIGN KEY \`FK_50375159f958ea3f33b7f2149dc\``);
        await queryRunner.query(`ALTER TABLE \`pages\` CHANGE \`page_icon\` \`page_icon\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` CHANGE \`modified_by\` \`modified_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pages\` CHANGE \`module_id\` \`module_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`modules\` CHANGE \`module_icon\` \`module_icon\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`modules\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`modules\` CHANGE \`modified_by\` \`modified_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_178199805b901ccd220ab7740ec\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_becd26d9c4332330de1cfed61a7\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`modified_by\` \`modified_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`role_id\` \`role_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`page_id\` \`page_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_permissions\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_permissions\` CHANGE \`modified_by\` \`modified_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`branches\` ADD CONSTRAINT \`FK_11a5e18b1a497189d0ec3cb5dac\` FOREIGN KEY (\`org_id\`) REFERENCES \`organisations\`(\`org_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD CONSTRAINT \`FK_50375159f958ea3f33b7f2149dc\` FOREIGN KEY (\`module_id\`) REFERENCES \`modules\`(\`module_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_178199805b901ccd220ab7740ec\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`role_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_becd26d9c4332330de1cfed61a7\` FOREIGN KEY (\`page_id\`) REFERENCES \`pages\`(\`page_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_becd26d9c4332330de1cfed61a7\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_178199805b901ccd220ab7740ec\``);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP FOREIGN KEY \`FK_50375159f958ea3f33b7f2149dc\``);
        await queryRunner.query(`ALTER TABLE \`branches\` DROP FOREIGN KEY \`FK_11a5e18b1a497189d0ec3cb5dac\``);
        await queryRunner.query(`ALTER TABLE \`user_permissions\` CHANGE \`modified_by\` \`modified_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_permissions\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`page_id\` \`page_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`role_id\` \`role_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`modified_by\` \`modified_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_becd26d9c4332330de1cfed61a7\` FOREIGN KEY (\`page_id\`) REFERENCES \`pages\`(\`page_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_178199805b901ccd220ab7740ec\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`role_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`modules\` CHANGE \`modified_by\` \`modified_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`modules\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`modules\` CHANGE \`module_icon\` \`module_icon\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pages\` CHANGE \`module_id\` \`module_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pages\` CHANGE \`modified_by\` \`modified_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pages\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pages\` CHANGE \`page_icon\` \`page_icon\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD CONSTRAINT \`FK_50375159f958ea3f33b7f2149dc\` FOREIGN KEY (\`module_id\`) REFERENCES \`modules\`(\`module_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`org_id\` \`org_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`modified_by\` \`modified_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`branches\` ADD CONSTRAINT \`FK_11a5e18b1a497189d0ec3cb5dac\` FOREIGN KEY (\`org_id\`) REFERENCES \`organisations\`(\`org_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`modified_by\` \`modified_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`contact_number\` \`contact_number\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`address\` \`address\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_logo\` \`org_logo\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_location\` \`org_location\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_email\` \`org_email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_phone\` \`org_phone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_pin\` \`org_pin\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_state_code\` \`org_state_code\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_city\` \`org_city\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`orgdistrict_number\` \`orgdistrict_number\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_FY\` \`org_FY\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_GSTIN_Number\` \`org_GSTIN_Number\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_PAN\` \`org_PAN\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_GST\` \`org_GST\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organisations\` CHANGE \`org_Reg_Number\` \`org_Reg_Number\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`modified_by\` \`modified_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`modified_by\` \`modified_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`DOB\` \`DOB\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`profile_poic\` \`profile_poic\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone_number\` \`phone_number\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`email\` \`email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`full_name\` \`full_name\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`organisations\` DROP COLUMN \`tin_number\``);
        await queryRunner.query(`ALTER TABLE \`organisations\` DROP COLUMN \`tan_number\``);
        await queryRunner.query(`ALTER TABLE \`organisations\` DROP COLUMN \`cash_account_number\``);
        await queryRunner.query(`ALTER TABLE \`organisations\` DROP COLUMN \`dept_logo\``);
        await queryRunner.query(`ALTER TABLE \`organisations\` DROP COLUMN \`service_tax\``);
        await queryRunner.query(`ALTER TABLE \`organisations\` DROP COLUMN \`wesite\``);
        await queryRunner.query(`ALTER TABLE \`organisations\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`organisations\` DROP COLUMN \`fax_number\``);
        await queryRunner.query(`ALTER TABLE \`organisations\` DROP COLUMN \`deducter_type\``);
        await queryRunner.query(`ALTER TABLE \`organisations\` DROP COLUMN \`enable_TDS_deduction\``);
        await queryRunner.query(`ALTER TABLE \`organisations\` DROP COLUMN \`org_charter_date\``);
        await queryRunner.query(`ALTER TABLE \`organisations\` DROP COLUMN \`document\``);
        await queryRunner.query(`ALTER TABLE \`organisations\` DROP COLUMN \`document_type\``);
        await queryRunner.query(`ALTER TABLE \`organisations\` DROP COLUMN \`org_registered_address\``);
        await queryRunner.query(`ALTER TABLE \`organisations\` DROP COLUMN \`org_TDS_deduction_type\``);
        await queryRunner.query(`ALTER TABLE \`organisations\` DROP COLUMN \`org_enable_TDS_deduction\``);
    }

}
